// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"

	"github.com/wso2/ai-agent-management-platform/agent-manager-service/clients/api-platform-svc/client"
)

// PlatformAPIClientMock is a mock implementation of client.PlatformAPIClient.
//
//	func TestSomethingThatUsesPlatformAPIClient(t *testing.T) {
//
//		// make and configure a mocked client.PlatformAPIClient
//		mockedPlatformAPIClient := &PlatformAPIClientMock{
//			CreateGatewayFunc: func(ctx context.Context, req client.CreateGatewayRequest) (*client.GatewayResponse, error) {
//				panic("mock out the CreateGateway method")
//			},
//			CreateLLMProviderFunc: func(ctx context.Context, req client.CreateLLMProviderRequest) (*client.LLMProviderResponse, error) {
//				panic("mock out the CreateLLMProvider method")
//			},
//			DeleteGatewayFunc: func(ctx context.Context, gatewayID string) error {
//				panic("mock out the DeleteGateway method")
//			},
//			DeleteLLMProviderFunc: func(ctx context.Context, providerID string) error {
//				panic("mock out the DeleteLLMProvider method")
//			},
//			GetGatewayFunc: func(ctx context.Context, gatewayID string) (*client.GatewayResponse, error) {
//				panic("mock out the GetGateway method")
//			},
//			GetLLMProviderFunc: func(ctx context.Context, providerID string) (*client.LLMProviderResponse, error) {
//				panic("mock out the GetLLMProvider method")
//			},
//			GetLLMProviderTemplateFunc: func(ctx context.Context, templateID string) (*client.LLMProviderTemplateResponse, error) {
//				panic("mock out the GetLLMProviderTemplate method")
//			},
//			HealthCheckFunc: func(ctx context.Context) error {
//				panic("mock out the HealthCheck method")
//			},
//			ListGatewaysFunc: func(ctx context.Context, filters client.GatewayFilters) (*client.GatewayListResponse, error) {
//				panic("mock out the ListGateways method")
//			},
//			ListLLMProviderTemplatesFunc: func(ctx context.Context, limit int32, offset int32) (*client.LLMProviderTemplateListResponse, error) {
//				panic("mock out the ListLLMProviderTemplates method")
//			},
//			ListLLMProvidersFunc: func(ctx context.Context, limit int32, offset int32) (*client.LLMProviderListResponse, error) {
//				panic("mock out the ListLLMProviders method")
//			},
//			RevokeGatewayTokenFunc: func(ctx context.Context, gatewayID string, tokenID string) error {
//				panic("mock out the RevokeGatewayToken method")
//			},
//			RotateGatewayTokenFunc: func(ctx context.Context, gatewayID string) (*client.TokenRotationResponse, error) {
//				panic("mock out the RotateGatewayToken method")
//			},
//			UpdateGatewayFunc: func(ctx context.Context, gatewayID string, req client.UpdateGatewayRequest) (*client.GatewayResponse, error) {
//				panic("mock out the UpdateGateway method")
//			},
//			UpdateLLMProviderFunc: func(ctx context.Context, providerID string, req client.UpdateLLMProviderRequest) (*client.LLMProviderResponse, error) {
//				panic("mock out the UpdateLLMProvider method")
//			},
//		}
//
//		// use mockedPlatformAPIClient in code that requires client.PlatformAPIClient
//		// and then make assertions.
//
//	}
type PlatformAPIClientMock struct {
	// CreateGatewayFunc mocks the CreateGateway method.
	CreateGatewayFunc func(ctx context.Context, req client.CreateGatewayRequest) (*client.GatewayResponse, error)

	// CreateLLMProviderFunc mocks the CreateLLMProvider method.
	CreateLLMProviderFunc func(ctx context.Context, req client.CreateLLMProviderRequest) (*client.LLMProviderResponse, error)

	// DeleteGatewayFunc mocks the DeleteGateway method.
	DeleteGatewayFunc func(ctx context.Context, gatewayID string) error

	// DeleteLLMProviderFunc mocks the DeleteLLMProvider method.
	DeleteLLMProviderFunc func(ctx context.Context, providerID string) error

	// GetGatewayFunc mocks the GetGateway method.
	GetGatewayFunc func(ctx context.Context, gatewayID string) (*client.GatewayResponse, error)

	// GetLLMProviderFunc mocks the GetLLMProvider method.
	GetLLMProviderFunc func(ctx context.Context, providerID string) (*client.LLMProviderResponse, error)

	// GetLLMProviderTemplateFunc mocks the GetLLMProviderTemplate method.
	GetLLMProviderTemplateFunc func(ctx context.Context, templateID string) (*client.LLMProviderTemplateResponse, error)

	// HealthCheckFunc mocks the HealthCheck method.
	HealthCheckFunc func(ctx context.Context) error

	// ListGatewaysFunc mocks the ListGateways method.
	ListGatewaysFunc func(ctx context.Context, filters client.GatewayFilters) (*client.GatewayListResponse, error)

	// ListLLMProviderTemplatesFunc mocks the ListLLMProviderTemplates method.
	ListLLMProviderTemplatesFunc func(ctx context.Context, limit int32, offset int32) (*client.LLMProviderTemplateListResponse, error)

	// ListLLMProvidersFunc mocks the ListLLMProviders method.
	ListLLMProvidersFunc func(ctx context.Context, limit int32, offset int32) (*client.LLMProviderListResponse, error)

	// RevokeGatewayTokenFunc mocks the RevokeGatewayToken method.
	RevokeGatewayTokenFunc func(ctx context.Context, gatewayID string, tokenID string) error

	// RotateGatewayTokenFunc mocks the RotateGatewayToken method.
	RotateGatewayTokenFunc func(ctx context.Context, gatewayID string) (*client.TokenRotationResponse, error)

	// UpdateGatewayFunc mocks the UpdateGateway method.
	UpdateGatewayFunc func(ctx context.Context, gatewayID string, req client.UpdateGatewayRequest) (*client.GatewayResponse, error)

	// UpdateLLMProviderFunc mocks the UpdateLLMProvider method.
	UpdateLLMProviderFunc func(ctx context.Context, providerID string, req client.UpdateLLMProviderRequest) (*client.LLMProviderResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateGateway holds details about calls to the CreateGateway method.
		CreateGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req client.CreateGatewayRequest
		}
		// CreateLLMProvider holds details about calls to the CreateLLMProvider method.
		CreateLLMProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req client.CreateLLMProviderRequest
		}
		// DeleteGateway holds details about calls to the DeleteGateway method.
		DeleteGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// DeleteLLMProvider holds details about calls to the DeleteLLMProvider method.
		DeleteLLMProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProviderID is the providerID argument value.
			ProviderID string
		}
		// GetGateway holds details about calls to the GetGateway method.
		GetGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// GetLLMProvider holds details about calls to the GetLLMProvider method.
		GetLLMProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProviderID is the providerID argument value.
			ProviderID string
		}
		// GetLLMProviderTemplate holds details about calls to the GetLLMProviderTemplate method.
		GetLLMProviderTemplate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TemplateID is the templateID argument value.
			TemplateID string
		}
		// HealthCheck holds details about calls to the HealthCheck method.
		HealthCheck []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListGateways holds details about calls to the ListGateways method.
		ListGateways []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filters is the filters argument value.
			Filters client.GatewayFilters
		}
		// ListLLMProviderTemplates holds details about calls to the ListLLMProviderTemplates method.
		ListLLMProviderTemplates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int32
			// Offset is the offset argument value.
			Offset int32
		}
		// ListLLMProviders holds details about calls to the ListLLMProviders method.
		ListLLMProviders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int32
			// Offset is the offset argument value.
			Offset int32
		}
		// RevokeGatewayToken holds details about calls to the RevokeGatewayToken method.
		RevokeGatewayToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// TokenID is the tokenID argument value.
			TokenID string
		}
		// RotateGatewayToken holds details about calls to the RotateGatewayToken method.
		RotateGatewayToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
		}
		// UpdateGateway holds details about calls to the UpdateGateway method.
		UpdateGateway []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayID is the gatewayID argument value.
			GatewayID string
			// Req is the req argument value.
			Req client.UpdateGatewayRequest
		}
		// UpdateLLMProvider holds details about calls to the UpdateLLMProvider method.
		UpdateLLMProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProviderID is the providerID argument value.
			ProviderID string
			// Req is the req argument value.
			Req client.UpdateLLMProviderRequest
		}
	}
	lockCreateGateway            sync.RWMutex
	lockCreateLLMProvider        sync.RWMutex
	lockDeleteGateway            sync.RWMutex
	lockDeleteLLMProvider        sync.RWMutex
	lockGetGateway               sync.RWMutex
	lockGetLLMProvider           sync.RWMutex
	lockGetLLMProviderTemplate   sync.RWMutex
	lockHealthCheck              sync.RWMutex
	lockListGateways             sync.RWMutex
	lockListLLMProviderTemplates sync.RWMutex
	lockListLLMProviders         sync.RWMutex
	lockRevokeGatewayToken       sync.RWMutex
	lockRotateGatewayToken       sync.RWMutex
	lockUpdateGateway            sync.RWMutex
	lockUpdateLLMProvider        sync.RWMutex
}

// CreateGateway calls CreateGatewayFunc.
func (mock *PlatformAPIClientMock) CreateGateway(ctx context.Context, req client.CreateGatewayRequest) (*client.GatewayResponse, error) {
	if mock.CreateGatewayFunc == nil {
		panic("PlatformAPIClientMock.CreateGatewayFunc: method is nil but PlatformAPIClient.CreateGateway was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req client.CreateGatewayRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateGateway.Lock()
	mock.calls.CreateGateway = append(mock.calls.CreateGateway, callInfo)
	mock.lockCreateGateway.Unlock()
	return mock.CreateGatewayFunc(ctx, req)
}

// CreateGatewayCalls gets all the calls that were made to CreateGateway.
// Check the length with:
//
//	len(mockedPlatformAPIClient.CreateGatewayCalls())
func (mock *PlatformAPIClientMock) CreateGatewayCalls() []struct {
	Ctx context.Context
	Req client.CreateGatewayRequest
} {
	var calls []struct {
		Ctx context.Context
		Req client.CreateGatewayRequest
	}
	mock.lockCreateGateway.RLock()
	calls = mock.calls.CreateGateway
	mock.lockCreateGateway.RUnlock()
	return calls
}

// CreateLLMProvider calls CreateLLMProviderFunc.
func (mock *PlatformAPIClientMock) CreateLLMProvider(ctx context.Context, req client.CreateLLMProviderRequest) (*client.LLMProviderResponse, error) {
	if mock.CreateLLMProviderFunc == nil {
		panic("PlatformAPIClientMock.CreateLLMProviderFunc: method is nil but PlatformAPIClient.CreateLLMProvider was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req client.CreateLLMProviderRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateLLMProvider.Lock()
	mock.calls.CreateLLMProvider = append(mock.calls.CreateLLMProvider, callInfo)
	mock.lockCreateLLMProvider.Unlock()
	return mock.CreateLLMProviderFunc(ctx, req)
}

// CreateLLMProviderCalls gets all the calls that were made to CreateLLMProvider.
// Check the length with:
//
//	len(mockedPlatformAPIClient.CreateLLMProviderCalls())
func (mock *PlatformAPIClientMock) CreateLLMProviderCalls() []struct {
	Ctx context.Context
	Req client.CreateLLMProviderRequest
} {
	var calls []struct {
		Ctx context.Context
		Req client.CreateLLMProviderRequest
	}
	mock.lockCreateLLMProvider.RLock()
	calls = mock.calls.CreateLLMProvider
	mock.lockCreateLLMProvider.RUnlock()
	return calls
}

// DeleteGateway calls DeleteGatewayFunc.
func (mock *PlatformAPIClientMock) DeleteGateway(ctx context.Context, gatewayID string) error {
	if mock.DeleteGatewayFunc == nil {
		panic("PlatformAPIClientMock.DeleteGatewayFunc: method is nil but PlatformAPIClient.DeleteGateway was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
	}
	mock.lockDeleteGateway.Lock()
	mock.calls.DeleteGateway = append(mock.calls.DeleteGateway, callInfo)
	mock.lockDeleteGateway.Unlock()
	return mock.DeleteGatewayFunc(ctx, gatewayID)
}

// DeleteGatewayCalls gets all the calls that were made to DeleteGateway.
// Check the length with:
//
//	len(mockedPlatformAPIClient.DeleteGatewayCalls())
func (mock *PlatformAPIClientMock) DeleteGatewayCalls() []struct {
	Ctx       context.Context
	GatewayID string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
	}
	mock.lockDeleteGateway.RLock()
	calls = mock.calls.DeleteGateway
	mock.lockDeleteGateway.RUnlock()
	return calls
}

// DeleteLLMProvider calls DeleteLLMProviderFunc.
func (mock *PlatformAPIClientMock) DeleteLLMProvider(ctx context.Context, providerID string) error {
	if mock.DeleteLLMProviderFunc == nil {
		panic("PlatformAPIClientMock.DeleteLLMProviderFunc: method is nil but PlatformAPIClient.DeleteLLMProvider was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProviderID string
	}{
		Ctx:        ctx,
		ProviderID: providerID,
	}
	mock.lockDeleteLLMProvider.Lock()
	mock.calls.DeleteLLMProvider = append(mock.calls.DeleteLLMProvider, callInfo)
	mock.lockDeleteLLMProvider.Unlock()
	return mock.DeleteLLMProviderFunc(ctx, providerID)
}

// DeleteLLMProviderCalls gets all the calls that were made to DeleteLLMProvider.
// Check the length with:
//
//	len(mockedPlatformAPIClient.DeleteLLMProviderCalls())
func (mock *PlatformAPIClientMock) DeleteLLMProviderCalls() []struct {
	Ctx        context.Context
	ProviderID string
} {
	var calls []struct {
		Ctx        context.Context
		ProviderID string
	}
	mock.lockDeleteLLMProvider.RLock()
	calls = mock.calls.DeleteLLMProvider
	mock.lockDeleteLLMProvider.RUnlock()
	return calls
}

// GetGateway calls GetGatewayFunc.
func (mock *PlatformAPIClientMock) GetGateway(ctx context.Context, gatewayID string) (*client.GatewayResponse, error) {
	if mock.GetGatewayFunc == nil {
		panic("PlatformAPIClientMock.GetGatewayFunc: method is nil but PlatformAPIClient.GetGateway was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
	}
	mock.lockGetGateway.Lock()
	mock.calls.GetGateway = append(mock.calls.GetGateway, callInfo)
	mock.lockGetGateway.Unlock()
	return mock.GetGatewayFunc(ctx, gatewayID)
}

// GetGatewayCalls gets all the calls that were made to GetGateway.
// Check the length with:
//
//	len(mockedPlatformAPIClient.GetGatewayCalls())
func (mock *PlatformAPIClientMock) GetGatewayCalls() []struct {
	Ctx       context.Context
	GatewayID string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
	}
	mock.lockGetGateway.RLock()
	calls = mock.calls.GetGateway
	mock.lockGetGateway.RUnlock()
	return calls
}

// GetLLMProvider calls GetLLMProviderFunc.
func (mock *PlatformAPIClientMock) GetLLMProvider(ctx context.Context, providerID string) (*client.LLMProviderResponse, error) {
	if mock.GetLLMProviderFunc == nil {
		panic("PlatformAPIClientMock.GetLLMProviderFunc: method is nil but PlatformAPIClient.GetLLMProvider was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProviderID string
	}{
		Ctx:        ctx,
		ProviderID: providerID,
	}
	mock.lockGetLLMProvider.Lock()
	mock.calls.GetLLMProvider = append(mock.calls.GetLLMProvider, callInfo)
	mock.lockGetLLMProvider.Unlock()
	return mock.GetLLMProviderFunc(ctx, providerID)
}

// GetLLMProviderCalls gets all the calls that were made to GetLLMProvider.
// Check the length with:
//
//	len(mockedPlatformAPIClient.GetLLMProviderCalls())
func (mock *PlatformAPIClientMock) GetLLMProviderCalls() []struct {
	Ctx        context.Context
	ProviderID string
} {
	var calls []struct {
		Ctx        context.Context
		ProviderID string
	}
	mock.lockGetLLMProvider.RLock()
	calls = mock.calls.GetLLMProvider
	mock.lockGetLLMProvider.RUnlock()
	return calls
}

// GetLLMProviderTemplate calls GetLLMProviderTemplateFunc.
func (mock *PlatformAPIClientMock) GetLLMProviderTemplate(ctx context.Context, templateID string) (*client.LLMProviderTemplateResponse, error) {
	if mock.GetLLMProviderTemplateFunc == nil {
		panic("PlatformAPIClientMock.GetLLMProviderTemplateFunc: method is nil but PlatformAPIClient.GetLLMProviderTemplate was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		TemplateID string
	}{
		Ctx:        ctx,
		TemplateID: templateID,
	}
	mock.lockGetLLMProviderTemplate.Lock()
	mock.calls.GetLLMProviderTemplate = append(mock.calls.GetLLMProviderTemplate, callInfo)
	mock.lockGetLLMProviderTemplate.Unlock()
	return mock.GetLLMProviderTemplateFunc(ctx, templateID)
}

// GetLLMProviderTemplateCalls gets all the calls that were made to GetLLMProviderTemplate.
// Check the length with:
//
//	len(mockedPlatformAPIClient.GetLLMProviderTemplateCalls())
func (mock *PlatformAPIClientMock) GetLLMProviderTemplateCalls() []struct {
	Ctx        context.Context
	TemplateID string
} {
	var calls []struct {
		Ctx        context.Context
		TemplateID string
	}
	mock.lockGetLLMProviderTemplate.RLock()
	calls = mock.calls.GetLLMProviderTemplate
	mock.lockGetLLMProviderTemplate.RUnlock()
	return calls
}

// HealthCheck calls HealthCheckFunc.
func (mock *PlatformAPIClientMock) HealthCheck(ctx context.Context) error {
	if mock.HealthCheckFunc == nil {
		panic("PlatformAPIClientMock.HealthCheckFunc: method is nil but PlatformAPIClient.HealthCheck was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockHealthCheck.Lock()
	mock.calls.HealthCheck = append(mock.calls.HealthCheck, callInfo)
	mock.lockHealthCheck.Unlock()
	return mock.HealthCheckFunc(ctx)
}

// HealthCheckCalls gets all the calls that were made to HealthCheck.
// Check the length with:
//
//	len(mockedPlatformAPIClient.HealthCheckCalls())
func (mock *PlatformAPIClientMock) HealthCheckCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockHealthCheck.RLock()
	calls = mock.calls.HealthCheck
	mock.lockHealthCheck.RUnlock()
	return calls
}

// ListGateways calls ListGatewaysFunc.
func (mock *PlatformAPIClientMock) ListGateways(ctx context.Context, filters client.GatewayFilters) (*client.GatewayListResponse, error) {
	if mock.ListGatewaysFunc == nil {
		panic("PlatformAPIClientMock.ListGatewaysFunc: method is nil but PlatformAPIClient.ListGateways was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Filters client.GatewayFilters
	}{
		Ctx:     ctx,
		Filters: filters,
	}
	mock.lockListGateways.Lock()
	mock.calls.ListGateways = append(mock.calls.ListGateways, callInfo)
	mock.lockListGateways.Unlock()
	return mock.ListGatewaysFunc(ctx, filters)
}

// ListGatewaysCalls gets all the calls that were made to ListGateways.
// Check the length with:
//
//	len(mockedPlatformAPIClient.ListGatewaysCalls())
func (mock *PlatformAPIClientMock) ListGatewaysCalls() []struct {
	Ctx     context.Context
	Filters client.GatewayFilters
} {
	var calls []struct {
		Ctx     context.Context
		Filters client.GatewayFilters
	}
	mock.lockListGateways.RLock()
	calls = mock.calls.ListGateways
	mock.lockListGateways.RUnlock()
	return calls
}

// ListLLMProviderTemplates calls ListLLMProviderTemplatesFunc.
func (mock *PlatformAPIClientMock) ListLLMProviderTemplates(ctx context.Context, limit int32, offset int32) (*client.LLMProviderTemplateListResponse, error) {
	if mock.ListLLMProviderTemplatesFunc == nil {
		panic("PlatformAPIClientMock.ListLLMProviderTemplatesFunc: method is nil but PlatformAPIClient.ListLLMProviderTemplates was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int32
		Offset int32
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListLLMProviderTemplates.Lock()
	mock.calls.ListLLMProviderTemplates = append(mock.calls.ListLLMProviderTemplates, callInfo)
	mock.lockListLLMProviderTemplates.Unlock()
	return mock.ListLLMProviderTemplatesFunc(ctx, limit, offset)
}

// ListLLMProviderTemplatesCalls gets all the calls that were made to ListLLMProviderTemplates.
// Check the length with:
//
//	len(mockedPlatformAPIClient.ListLLMProviderTemplatesCalls())
func (mock *PlatformAPIClientMock) ListLLMProviderTemplatesCalls() []struct {
	Ctx    context.Context
	Limit  int32
	Offset int32
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int32
		Offset int32
	}
	mock.lockListLLMProviderTemplates.RLock()
	calls = mock.calls.ListLLMProviderTemplates
	mock.lockListLLMProviderTemplates.RUnlock()
	return calls
}

// ListLLMProviders calls ListLLMProvidersFunc.
func (mock *PlatformAPIClientMock) ListLLMProviders(ctx context.Context, limit int32, offset int32) (*client.LLMProviderListResponse, error) {
	if mock.ListLLMProvidersFunc == nil {
		panic("PlatformAPIClientMock.ListLLMProvidersFunc: method is nil but PlatformAPIClient.ListLLMProviders was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int32
		Offset int32
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListLLMProviders.Lock()
	mock.calls.ListLLMProviders = append(mock.calls.ListLLMProviders, callInfo)
	mock.lockListLLMProviders.Unlock()
	return mock.ListLLMProvidersFunc(ctx, limit, offset)
}

// ListLLMProvidersCalls gets all the calls that were made to ListLLMProviders.
// Check the length with:
//
//	len(mockedPlatformAPIClient.ListLLMProvidersCalls())
func (mock *PlatformAPIClientMock) ListLLMProvidersCalls() []struct {
	Ctx    context.Context
	Limit  int32
	Offset int32
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int32
		Offset int32
	}
	mock.lockListLLMProviders.RLock()
	calls = mock.calls.ListLLMProviders
	mock.lockListLLMProviders.RUnlock()
	return calls
}

// RevokeGatewayToken calls RevokeGatewayTokenFunc.
func (mock *PlatformAPIClientMock) RevokeGatewayToken(ctx context.Context, gatewayID string, tokenID string) error {
	if mock.RevokeGatewayTokenFunc == nil {
		panic("PlatformAPIClientMock.RevokeGatewayTokenFunc: method is nil but PlatformAPIClient.RevokeGatewayToken was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
		TokenID   string
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
		TokenID:   tokenID,
	}
	mock.lockRevokeGatewayToken.Lock()
	mock.calls.RevokeGatewayToken = append(mock.calls.RevokeGatewayToken, callInfo)
	mock.lockRevokeGatewayToken.Unlock()
	return mock.RevokeGatewayTokenFunc(ctx, gatewayID, tokenID)
}

// RevokeGatewayTokenCalls gets all the calls that were made to RevokeGatewayToken.
// Check the length with:
//
//	len(mockedPlatformAPIClient.RevokeGatewayTokenCalls())
func (mock *PlatformAPIClientMock) RevokeGatewayTokenCalls() []struct {
	Ctx       context.Context
	GatewayID string
	TokenID   string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
		TokenID   string
	}
	mock.lockRevokeGatewayToken.RLock()
	calls = mock.calls.RevokeGatewayToken
	mock.lockRevokeGatewayToken.RUnlock()
	return calls
}

// RotateGatewayToken calls RotateGatewayTokenFunc.
func (mock *PlatformAPIClientMock) RotateGatewayToken(ctx context.Context, gatewayID string) (*client.TokenRotationResponse, error) {
	if mock.RotateGatewayTokenFunc == nil {
		panic("PlatformAPIClientMock.RotateGatewayTokenFunc: method is nil but PlatformAPIClient.RotateGatewayToken was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
	}
	mock.lockRotateGatewayToken.Lock()
	mock.calls.RotateGatewayToken = append(mock.calls.RotateGatewayToken, callInfo)
	mock.lockRotateGatewayToken.Unlock()
	return mock.RotateGatewayTokenFunc(ctx, gatewayID)
}

// RotateGatewayTokenCalls gets all the calls that were made to RotateGatewayToken.
// Check the length with:
//
//	len(mockedPlatformAPIClient.RotateGatewayTokenCalls())
func (mock *PlatformAPIClientMock) RotateGatewayTokenCalls() []struct {
	Ctx       context.Context
	GatewayID string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
	}
	mock.lockRotateGatewayToken.RLock()
	calls = mock.calls.RotateGatewayToken
	mock.lockRotateGatewayToken.RUnlock()
	return calls
}

// UpdateGateway calls UpdateGatewayFunc.
func (mock *PlatformAPIClientMock) UpdateGateway(ctx context.Context, gatewayID string, req client.UpdateGatewayRequest) (*client.GatewayResponse, error) {
	if mock.UpdateGatewayFunc == nil {
		panic("PlatformAPIClientMock.UpdateGatewayFunc: method is nil but PlatformAPIClient.UpdateGateway was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayID string
		Req       client.UpdateGatewayRequest
	}{
		Ctx:       ctx,
		GatewayID: gatewayID,
		Req:       req,
	}
	mock.lockUpdateGateway.Lock()
	mock.calls.UpdateGateway = append(mock.calls.UpdateGateway, callInfo)
	mock.lockUpdateGateway.Unlock()
	return mock.UpdateGatewayFunc(ctx, gatewayID, req)
}

// UpdateGatewayCalls gets all the calls that were made to UpdateGateway.
// Check the length with:
//
//	len(mockedPlatformAPIClient.UpdateGatewayCalls())
func (mock *PlatformAPIClientMock) UpdateGatewayCalls() []struct {
	Ctx       context.Context
	GatewayID string
	Req       client.UpdateGatewayRequest
} {
	var calls []struct {
		Ctx       context.Context
		GatewayID string
		Req       client.UpdateGatewayRequest
	}
	mock.lockUpdateGateway.RLock()
	calls = mock.calls.UpdateGateway
	mock.lockUpdateGateway.RUnlock()
	return calls
}

// UpdateLLMProvider calls UpdateLLMProviderFunc.
func (mock *PlatformAPIClientMock) UpdateLLMProvider(ctx context.Context, providerID string, req client.UpdateLLMProviderRequest) (*client.LLMProviderResponse, error) {
	if mock.UpdateLLMProviderFunc == nil {
		panic("PlatformAPIClientMock.UpdateLLMProviderFunc: method is nil but PlatformAPIClient.UpdateLLMProvider was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProviderID string
		Req        client.UpdateLLMProviderRequest
	}{
		Ctx:        ctx,
		ProviderID: providerID,
		Req:        req,
	}
	mock.lockUpdateLLMProvider.Lock()
	mock.calls.UpdateLLMProvider = append(mock.calls.UpdateLLMProvider, callInfo)
	mock.lockUpdateLLMProvider.Unlock()
	return mock.UpdateLLMProviderFunc(ctx, providerID, req)
}

// UpdateLLMProviderCalls gets all the calls that were made to UpdateLLMProvider.
// Check the length with:
//
//	len(mockedPlatformAPIClient.UpdateLLMProviderCalls())
func (mock *PlatformAPIClientMock) UpdateLLMProviderCalls() []struct {
	Ctx        context.Context
	ProviderID string
	Req        client.UpdateLLMProviderRequest
} {
	var calls []struct {
		Ctx        context.Context
		ProviderID string
		Req        client.UpdateLLMProviderRequest
	}
	mock.lockUpdateLLMProvider.RLock()
	calls = mock.calls.UpdateLLMProvider
	mock.lockUpdateLLMProvider.RUnlock()
	return calls
}
