/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GetGatewayEnvironments200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGatewayEnvironments200Response{}

// GetGatewayEnvironments200Response struct for GetGatewayEnvironments200Response
type GetGatewayEnvironments200Response struct {
	Environments []EnvironmentResponse `json:"environments"`
	Total        int32                 `json:"total"`
}

// NewGetGatewayEnvironments200Response instantiates a new GetGatewayEnvironments200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGatewayEnvironments200Response(environments []EnvironmentResponse, total int32) *GetGatewayEnvironments200Response {
	this := GetGatewayEnvironments200Response{}
	this.Environments = environments
	this.Total = total
	return &this
}

// NewGetGatewayEnvironments200ResponseWithDefaults instantiates a new GetGatewayEnvironments200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGatewayEnvironments200ResponseWithDefaults() *GetGatewayEnvironments200Response {
	this := GetGatewayEnvironments200Response{}
	return &this
}

// GetEnvironments returns the Environments field value
func (o *GetGatewayEnvironments200Response) GetEnvironments() []EnvironmentResponse {
	if o == nil {
		var ret []EnvironmentResponse
		return ret
	}

	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value
// and a boolean to check if the value has been set.
func (o *GetGatewayEnvironments200Response) GetEnvironmentsOk() ([]EnvironmentResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environments, true
}

// SetEnvironments sets field value
func (o *GetGatewayEnvironments200Response) SetEnvironments(v []EnvironmentResponse) {
	o.Environments = v
}

// GetTotal returns the Total field value
func (o *GetGatewayEnvironments200Response) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetGatewayEnvironments200Response) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetGatewayEnvironments200Response) SetTotal(v int32) {
	o.Total = v
}

func (o GetGatewayEnvironments200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGatewayEnvironments200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environments"] = o.Environments
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

type NullableGetGatewayEnvironments200Response struct {
	value *GetGatewayEnvironments200Response
	isSet bool
}

func (v NullableGetGatewayEnvironments200Response) Get() *GetGatewayEnvironments200Response {
	return v.value
}

func (v *NullableGetGatewayEnvironments200Response) Set(val *GetGatewayEnvironments200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGatewayEnvironments200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGatewayEnvironments200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGatewayEnvironments200Response(val *GetGatewayEnvironments200Response) *NullableGetGatewayEnvironments200Response {
	return &NullableGetGatewayEnvironments200Response{value: val, isSet: true}
}

func (v NullableGetGatewayEnvironments200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGatewayEnvironments200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
