/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the EnvironmentSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentSummary{}

// EnvironmentSummary struct for EnvironmentSummary
type EnvironmentSummary struct {
	// Environment UUID
	Uuid string `json:"uuid"`
	// Environment name
	Name string `json:"name"`
	// Environment display name
	DisplayName string `json:"displayName"`
}

// NewEnvironmentSummary instantiates a new EnvironmentSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentSummary(uuid string, name string, displayName string) *EnvironmentSummary {
	this := EnvironmentSummary{}
	this.Uuid = uuid
	this.Name = name
	this.DisplayName = displayName
	return &this
}

// NewEnvironmentSummaryWithDefaults instantiates a new EnvironmentSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentSummaryWithDefaults() *EnvironmentSummary {
	this := EnvironmentSummary{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *EnvironmentSummary) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *EnvironmentSummary) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *EnvironmentSummary) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *EnvironmentSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EnvironmentSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EnvironmentSummary) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *EnvironmentSummary) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *EnvironmentSummary) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *EnvironmentSummary) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o EnvironmentSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	return toSerialize, nil
}

type NullableEnvironmentSummary struct {
	value *EnvironmentSummary
	isSet bool
}

func (v NullableEnvironmentSummary) Get() *EnvironmentSummary {
	return v.value
}

func (v *NullableEnvironmentSummary) Set(val *EnvironmentSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentSummary(val *EnvironmentSummary) *NullableEnvironmentSummary {
	return &NullableEnvironmentSummary{value: val, isSet: true}
}

func (v NullableEnvironmentSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
