/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GetEnvironmentGateways200ResponseMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEnvironmentGateways200ResponseMetadata{}

// GetEnvironmentGateways200ResponseMetadata Additional metadata
type GetEnvironmentGateways200ResponseMetadata struct {
	// Number of orphaned mappings cleaned up
	OrphanedMappingsRemoved *int32 `json:"orphanedMappingsRemoved,omitempty"`
}

// NewGetEnvironmentGateways200ResponseMetadata instantiates a new GetEnvironmentGateways200ResponseMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEnvironmentGateways200ResponseMetadata() *GetEnvironmentGateways200ResponseMetadata {
	this := GetEnvironmentGateways200ResponseMetadata{}
	return &this
}

// NewGetEnvironmentGateways200ResponseMetadataWithDefaults instantiates a new GetEnvironmentGateways200ResponseMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEnvironmentGateways200ResponseMetadataWithDefaults() *GetEnvironmentGateways200ResponseMetadata {
	this := GetEnvironmentGateways200ResponseMetadata{}
	return &this
}

// GetOrphanedMappingsRemoved returns the OrphanedMappingsRemoved field value if set, zero value otherwise.
func (o *GetEnvironmentGateways200ResponseMetadata) GetOrphanedMappingsRemoved() int32 {
	if o == nil || IsNil(o.OrphanedMappingsRemoved) {
		var ret int32
		return ret
	}
	return *o.OrphanedMappingsRemoved
}

// GetOrphanedMappingsRemovedOk returns a tuple with the OrphanedMappingsRemoved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEnvironmentGateways200ResponseMetadata) GetOrphanedMappingsRemovedOk() (*int32, bool) {
	if o == nil || IsNil(o.OrphanedMappingsRemoved) {
		return nil, false
	}
	return o.OrphanedMappingsRemoved, true
}

// HasOrphanedMappingsRemoved returns a boolean if a field has been set.
func (o *GetEnvironmentGateways200ResponseMetadata) HasOrphanedMappingsRemoved() bool {
	if o != nil && !IsNil(o.OrphanedMappingsRemoved) {
		return true
	}

	return false
}

// SetOrphanedMappingsRemoved gets a reference to the given int32 and assigns it to the OrphanedMappingsRemoved field.
func (o *GetEnvironmentGateways200ResponseMetadata) SetOrphanedMappingsRemoved(v int32) {
	o.OrphanedMappingsRemoved = &v
}

func (o GetEnvironmentGateways200ResponseMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEnvironmentGateways200ResponseMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrphanedMappingsRemoved) {
		toSerialize["orphanedMappingsRemoved"] = o.OrphanedMappingsRemoved
	}
	return toSerialize, nil
}

type NullableGetEnvironmentGateways200ResponseMetadata struct {
	value *GetEnvironmentGateways200ResponseMetadata
	isSet bool
}

func (v NullableGetEnvironmentGateways200ResponseMetadata) Get() *GetEnvironmentGateways200ResponseMetadata {
	return v.value
}

func (v *NullableGetEnvironmentGateways200ResponseMetadata) Set(val *GetEnvironmentGateways200ResponseMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEnvironmentGateways200ResponseMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEnvironmentGateways200ResponseMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEnvironmentGateways200ResponseMetadata(val *GetEnvironmentGateways200ResponseMetadata) *NullableGetEnvironmentGateways200ResponseMetadata {
	return &NullableGetEnvironmentGateways200ResponseMetadata{value: val, isSet: true}
}

func (v NullableGetEnvironmentGateways200ResponseMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEnvironmentGateways200ResponseMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
