/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateGatewayRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGatewayRequest{}

// UpdateGatewayRequest struct for UpdateGatewayRequest
type UpdateGatewayRequest struct {
	// Updated display name
	DisplayName *string `json:"displayName,omitempty"`
}

// NewUpdateGatewayRequest instantiates a new UpdateGatewayRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGatewayRequest() *UpdateGatewayRequest {
	this := UpdateGatewayRequest{}
	return &this
}

// NewUpdateGatewayRequestWithDefaults instantiates a new UpdateGatewayRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGatewayRequestWithDefaults() *UpdateGatewayRequest {
	this := UpdateGatewayRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *UpdateGatewayRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGatewayRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UpdateGatewayRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *UpdateGatewayRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

func (o UpdateGatewayRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGatewayRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	return toSerialize, nil
}

type NullableUpdateGatewayRequest struct {
	value *UpdateGatewayRequest
	isSet bool
}

func (v NullableUpdateGatewayRequest) Get() *UpdateGatewayRequest {
	return v.value
}

func (v *NullableUpdateGatewayRequest) Set(val *UpdateGatewayRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGatewayRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGatewayRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGatewayRequest(val *UpdateGatewayRequest) *NullableUpdateGatewayRequest {
	return &NullableUpdateGatewayRequest{value: val, isSet: true}
}

func (v NullableUpdateGatewayRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGatewayRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
