/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the CreateLLMProviderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLLMProviderRequest{}

// CreateLLMProviderRequest struct for CreateLLMProviderRequest
type CreateLLMProviderRequest struct {
	// Unique provider identifier
	Id string `json:"id"`
	// Provider name
	Name string `json:"name"`
	// Provider version
	Version string `json:"version"`
	// Template name (e.g., \"openai\")
	Template string `json:"template"`
	// Upstream configuration
	Upstream map[string]interface{} `json:"upstream"`
	// Provider description
	Description *string `json:"description,omitempty"`
	// Deployment context
	Context *string `json:"context,omitempty"`
	// Virtual host for provider
	Vhost string `json:"vhost"`
	// Gateway UUIDs to deploy provider to
	GatewayIds []string `json:"gatewayIds,omitempty"`
}

// NewCreateLLMProviderRequest instantiates a new CreateLLMProviderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLLMProviderRequest(id string, name string, version string, template string, upstream map[string]interface{}, vhost string) *CreateLLMProviderRequest {
	this := CreateLLMProviderRequest{}
	this.Id = id
	this.Name = name
	this.Version = version
	this.Template = template
	this.Upstream = upstream
	this.Vhost = vhost
	return &this
}

// NewCreateLLMProviderRequestWithDefaults instantiates a new CreateLLMProviderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLLMProviderRequestWithDefaults() *CreateLLMProviderRequest {
	this := CreateLLMProviderRequest{}
	return &this
}

// GetId returns the Id field value
func (o *CreateLLMProviderRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateLLMProviderRequest) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CreateLLMProviderRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateLLMProviderRequest) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *CreateLLMProviderRequest) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CreateLLMProviderRequest) SetVersion(v string) {
	o.Version = v
}

// GetTemplate returns the Template field value
func (o *CreateLLMProviderRequest) GetTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *CreateLLMProviderRequest) SetTemplate(v string) {
	o.Template = v
}

// GetUpstream returns the Upstream field value
func (o *CreateLLMProviderRequest) GetUpstream() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Upstream
}

// GetUpstreamOk returns a tuple with the Upstream field value
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetUpstreamOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Upstream, true
}

// SetUpstream sets field value
func (o *CreateLLMProviderRequest) SetUpstream(v map[string]interface{}) {
	o.Upstream = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateLLMProviderRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateLLMProviderRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateLLMProviderRequest) SetDescription(v string) {
	o.Description = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *CreateLLMProviderRequest) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *CreateLLMProviderRequest) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *CreateLLMProviderRequest) SetContext(v string) {
	o.Context = &v
}

// GetVhost returns the Vhost field value
func (o *CreateLLMProviderRequest) GetVhost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vhost
}

// GetVhostOk returns a tuple with the Vhost field value
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetVhostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vhost, true
}

// SetVhost sets field value
func (o *CreateLLMProviderRequest) SetVhost(v string) {
	o.Vhost = v
}

// GetGatewayIds returns the GatewayIds field value if set, zero value otherwise.
func (o *CreateLLMProviderRequest) GetGatewayIds() []string {
	if o == nil || IsNil(o.GatewayIds) {
		var ret []string
		return ret
	}
	return o.GatewayIds
}

// GetGatewayIdsOk returns a tuple with the GatewayIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLLMProviderRequest) GetGatewayIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.GatewayIds) {
		return nil, false
	}
	return o.GatewayIds, true
}

// HasGatewayIds returns a boolean if a field has been set.
func (o *CreateLLMProviderRequest) HasGatewayIds() bool {
	if o != nil && !IsNil(o.GatewayIds) {
		return true
	}

	return false
}

// SetGatewayIds gets a reference to the given []string and assigns it to the GatewayIds field.
func (o *CreateLLMProviderRequest) SetGatewayIds(v []string) {
	o.GatewayIds = v
}

func (o CreateLLMProviderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLLMProviderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["template"] = o.Template
	toSerialize["upstream"] = o.Upstream
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	toSerialize["vhost"] = o.Vhost
	if !IsNil(o.GatewayIds) {
		toSerialize["gatewayIds"] = o.GatewayIds
	}
	return toSerialize, nil
}

type NullableCreateLLMProviderRequest struct {
	value *CreateLLMProviderRequest
	isSet bool
}

func (v NullableCreateLLMProviderRequest) Get() *CreateLLMProviderRequest {
	return v.value
}

func (v *NullableCreateLLMProviderRequest) Set(val *CreateLLMProviderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLLMProviderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLLMProviderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLLMProviderRequest(val *CreateLLMProviderRequest) *NullableCreateLLMProviderRequest {
	return &NullableCreateLLMProviderRequest{value: val, isSet: true}
}

func (v NullableCreateLLMProviderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLLMProviderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
