/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the EnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentResponse{}

// EnvironmentResponse struct for EnvironmentResponse
type EnvironmentResponse struct {
	// Unique identifier for the environment
	Uuid string `json:"uuid"`
	// Organization UUID
	OrganizationId string `json:"organizationId"`
	// Unique environment name
	Name string `json:"name"`
	// Human-readable display name
	DisplayName string `json:"displayName"`
	// Environment description
	Description *string `json:"description,omitempty"`
	// Timestamp when environment was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when environment was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// NewEnvironmentResponse instantiates a new EnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentResponse(uuid string, organizationId string, name string, displayName string, createdAt time.Time, updatedAt time.Time) *EnvironmentResponse {
	this := EnvironmentResponse{}
	this.Uuid = uuid
	this.OrganizationId = organizationId
	this.Name = name
	this.DisplayName = displayName
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewEnvironmentResponseWithDefaults instantiates a new EnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentResponseWithDefaults() *EnvironmentResponse {
	this := EnvironmentResponse{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *EnvironmentResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *EnvironmentResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *EnvironmentResponse) SetUuid(v string) {
	o.Uuid = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *EnvironmentResponse) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *EnvironmentResponse) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *EnvironmentResponse) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetName returns the Name field value
func (o *EnvironmentResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EnvironmentResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EnvironmentResponse) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *EnvironmentResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *EnvironmentResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *EnvironmentResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EnvironmentResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EnvironmentResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EnvironmentResponse) SetDescription(v string) {
	o.Description = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EnvironmentResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EnvironmentResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EnvironmentResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *EnvironmentResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *EnvironmentResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *EnvironmentResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o EnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

type NullableEnvironmentResponse struct {
	value *EnvironmentResponse
	isSet bool
}

func (v NullableEnvironmentResponse) Get() *EnvironmentResponse {
	return v.value
}

func (v *NullableEnvironmentResponse) Set(val *EnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentResponse(val *EnvironmentResponse) *NullableEnvironmentResponse {
	return &NullableEnvironmentResponse{value: val, isSet: true}
}

func (v NullableEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
