/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GetEnvironmentGateways200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEnvironmentGateways200Response{}

// GetEnvironmentGateways200Response struct for GetEnvironmentGateways200Response
type GetEnvironmentGateways200Response struct {
	Gateways []GatewayResponse `json:"gateways"`
	// Total number of gateways
	Total    int32                                      `json:"total"`
	Metadata *GetEnvironmentGateways200ResponseMetadata `json:"metadata,omitempty"`
}

// NewGetEnvironmentGateways200Response instantiates a new GetEnvironmentGateways200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEnvironmentGateways200Response(gateways []GatewayResponse, total int32) *GetEnvironmentGateways200Response {
	this := GetEnvironmentGateways200Response{}
	this.Gateways = gateways
	this.Total = total
	return &this
}

// NewGetEnvironmentGateways200ResponseWithDefaults instantiates a new GetEnvironmentGateways200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEnvironmentGateways200ResponseWithDefaults() *GetEnvironmentGateways200Response {
	this := GetEnvironmentGateways200Response{}
	return &this
}

// GetGateways returns the Gateways field value
func (o *GetEnvironmentGateways200Response) GetGateways() []GatewayResponse {
	if o == nil {
		var ret []GatewayResponse
		return ret
	}

	return o.Gateways
}

// GetGatewaysOk returns a tuple with the Gateways field value
// and a boolean to check if the value has been set.
func (o *GetEnvironmentGateways200Response) GetGatewaysOk() ([]GatewayResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gateways, true
}

// SetGateways sets field value
func (o *GetEnvironmentGateways200Response) SetGateways(v []GatewayResponse) {
	o.Gateways = v
}

// GetTotal returns the Total field value
func (o *GetEnvironmentGateways200Response) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetEnvironmentGateways200Response) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetEnvironmentGateways200Response) SetTotal(v int32) {
	o.Total = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GetEnvironmentGateways200Response) GetMetadata() GetEnvironmentGateways200ResponseMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret GetEnvironmentGateways200ResponseMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEnvironmentGateways200Response) GetMetadataOk() (*GetEnvironmentGateways200ResponseMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GetEnvironmentGateways200Response) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given GetEnvironmentGateways200ResponseMetadata and assigns it to the Metadata field.
func (o *GetEnvironmentGateways200Response) SetMetadata(v GetEnvironmentGateways200ResponseMetadata) {
	o.Metadata = &v
}

func (o GetEnvironmentGateways200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEnvironmentGateways200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gateways"] = o.Gateways
	toSerialize["total"] = o.Total
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableGetEnvironmentGateways200Response struct {
	value *GetEnvironmentGateways200Response
	isSet bool
}

func (v NullableGetEnvironmentGateways200Response) Get() *GetEnvironmentGateways200Response {
	return v.value
}

func (v *NullableGetEnvironmentGateways200Response) Set(val *GetEnvironmentGateways200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEnvironmentGateways200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEnvironmentGateways200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEnvironmentGateways200Response(val *GetEnvironmentGateways200Response) *NullableGetEnvironmentGateways200Response {
	return &NullableGetEnvironmentGateways200Response{value: val, isSet: true}
}

func (v NullableGetEnvironmentGateways200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEnvironmentGateways200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
