/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GatewayListResponseMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayListResponseMetadata{}

// GatewayListResponseMetadata Additional metadata (e.g., orphaned mappings removed)
type GatewayListResponseMetadata struct {
	// Number of orphaned mappings cleaned up
	OrphanedMappingsRemoved *int32 `json:"orphanedMappingsRemoved,omitempty"`
}

// NewGatewayListResponseMetadata instantiates a new GatewayListResponseMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayListResponseMetadata() *GatewayListResponseMetadata {
	this := GatewayListResponseMetadata{}
	return &this
}

// NewGatewayListResponseMetadataWithDefaults instantiates a new GatewayListResponseMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayListResponseMetadataWithDefaults() *GatewayListResponseMetadata {
	this := GatewayListResponseMetadata{}
	return &this
}

// GetOrphanedMappingsRemoved returns the OrphanedMappingsRemoved field value if set, zero value otherwise.
func (o *GatewayListResponseMetadata) GetOrphanedMappingsRemoved() int32 {
	if o == nil || IsNil(o.OrphanedMappingsRemoved) {
		var ret int32
		return ret
	}
	return *o.OrphanedMappingsRemoved
}

// GetOrphanedMappingsRemovedOk returns a tuple with the OrphanedMappingsRemoved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayListResponseMetadata) GetOrphanedMappingsRemovedOk() (*int32, bool) {
	if o == nil || IsNil(o.OrphanedMappingsRemoved) {
		return nil, false
	}
	return o.OrphanedMappingsRemoved, true
}

// HasOrphanedMappingsRemoved returns a boolean if a field has been set.
func (o *GatewayListResponseMetadata) HasOrphanedMappingsRemoved() bool {
	if o != nil && !IsNil(o.OrphanedMappingsRemoved) {
		return true
	}

	return false
}

// SetOrphanedMappingsRemoved gets a reference to the given int32 and assigns it to the OrphanedMappingsRemoved field.
func (o *GatewayListResponseMetadata) SetOrphanedMappingsRemoved(v int32) {
	o.OrphanedMappingsRemoved = &v
}

func (o GatewayListResponseMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayListResponseMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrphanedMappingsRemoved) {
		toSerialize["orphanedMappingsRemoved"] = o.OrphanedMappingsRemoved
	}
	return toSerialize, nil
}

type NullableGatewayListResponseMetadata struct {
	value *GatewayListResponseMetadata
	isSet bool
}

func (v NullableGatewayListResponseMetadata) Get() *GatewayListResponseMetadata {
	return v.value
}

func (v *NullableGatewayListResponseMetadata) Set(val *GatewayListResponseMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayListResponseMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayListResponseMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayListResponseMetadata(val *GatewayListResponseMetadata) *NullableGatewayListResponseMetadata {
	return &NullableGatewayListResponseMetadata{value: val, isSet: true}
}

func (v NullableGatewayListResponseMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayListResponseMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
