/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GatewaySummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewaySummary{}

// GatewaySummary struct for GatewaySummary
type GatewaySummary struct {
	// Gateway UUID
	Uuid string `json:"uuid"`
	// Gateway name
	Name string `json:"name"`
	// Gateway display name
	DisplayName string `json:"displayName"`
}

// NewGatewaySummary instantiates a new GatewaySummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewaySummary(uuid string, name string, displayName string) *GatewaySummary {
	this := GatewaySummary{}
	this.Uuid = uuid
	this.Name = name
	this.DisplayName = displayName
	return &this
}

// NewGatewaySummaryWithDefaults instantiates a new GatewaySummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewaySummaryWithDefaults() *GatewaySummary {
	this := GatewaySummary{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *GatewaySummary) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *GatewaySummary) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *GatewaySummary) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *GatewaySummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GatewaySummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GatewaySummary) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *GatewaySummary) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *GatewaySummary) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *GatewaySummary) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o GatewaySummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewaySummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	return toSerialize, nil
}

type NullableGatewaySummary struct {
	value *GatewaySummary
	isSet bool
}

func (v NullableGatewaySummary) Get() *GatewaySummary {
	return v.value
}

func (v *NullableGatewaySummary) Set(val *GatewaySummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewaySummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewaySummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewaySummary(val *GatewaySummary) *NullableGatewaySummary {
	return &NullableGatewaySummary{value: val, isSet: true}
}

func (v NullableGatewaySummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewaySummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
