/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the Resilience type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Resilience{}

// Resilience Route-level request/idle timeouts applied at the API level (no per-operation override for LLM providers, LLM proxies, or MCP proxies).
type Resilience struct {
	// Max duration for the whole request→upstream-response. \"0s\" disables it; omit to use the gateway's default.
	Timeout *string `json:"timeout,omitempty"`
	// Per-route stream idle timeout. \"0s\" disables it; omit to use the gateway's default.
	IdleTimeout *string `json:"idleTimeout,omitempty"`
}

// NewResilience instantiates a new Resilience object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResilience() *Resilience {
	this := Resilience{}
	return &this
}

// NewResilienceWithDefaults instantiates a new Resilience object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResilienceWithDefaults() *Resilience {
	this := Resilience{}
	return &this
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *Resilience) GetTimeout() string {
	if o == nil || IsNil(o.Timeout) {
		var ret string
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resilience) GetTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *Resilience) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given string and assigns it to the Timeout field.
func (o *Resilience) SetTimeout(v string) {
	o.Timeout = &v
}

// GetIdleTimeout returns the IdleTimeout field value if set, zero value otherwise.
func (o *Resilience) GetIdleTimeout() string {
	if o == nil || IsNil(o.IdleTimeout) {
		var ret string
		return ret
	}
	return *o.IdleTimeout
}

// GetIdleTimeoutOk returns a tuple with the IdleTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resilience) GetIdleTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.IdleTimeout) {
		return nil, false
	}
	return o.IdleTimeout, true
}

// HasIdleTimeout returns a boolean if a field has been set.
func (o *Resilience) HasIdleTimeout() bool {
	if o != nil && !IsNil(o.IdleTimeout) {
		return true
	}

	return false
}

// SetIdleTimeout gets a reference to the given string and assigns it to the IdleTimeout field.
func (o *Resilience) SetIdleTimeout(v string) {
	o.IdleTimeout = &v
}

func (o Resilience) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Resilience) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.IdleTimeout) {
		toSerialize["idleTimeout"] = o.IdleTimeout
	}
	return toSerialize, nil
}

type NullableResilience struct {
	value *Resilience
	isSet bool
}

func (v NullableResilience) Get() *Resilience {
	return v.value
}

func (v *NullableResilience) Set(val *Resilience) {
	v.value = val
	v.isSet = true
}

func (v NullableResilience) IsSet() bool {
	return v.isSet
}

func (v *NullableResilience) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResilience(val *Resilience) *NullableResilience {
	return &NullableResilience{value: val, isSet: true}
}

func (v NullableResilience) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResilience) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
