/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the LLMProviderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMProviderResponse{}

// LLMProviderResponse struct for LLMProviderResponse
type LLMProviderResponse struct {
	// Provider ID
	Id string `json:"id"`
	// Provider name
	Name string `json:"name"`
	// Provider version
	Version string `json:"version"`
	// Template name
	Template string `json:"template"`
	// Upstream configuration
	Upstream map[string]interface{} `json:"upstream,omitempty"`
	// Provider description
	Description *string `json:"description,omitempty"`
	// Deployment context
	Context *string `json:"context,omitempty"`
	// Virtual host
	Vhost     string    `json:"vhost"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	// Gateways associated with provider
	Gateways []GatewaySummary `json:"gateways,omitempty"`
}

// NewLLMProviderResponse instantiates a new LLMProviderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMProviderResponse(id string, name string, version string, template string, vhost string, createdAt time.Time, updatedAt time.Time) *LLMProviderResponse {
	this := LLMProviderResponse{}
	this.Id = id
	this.Name = name
	this.Version = version
	this.Template = template
	this.Vhost = vhost
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewLLMProviderResponseWithDefaults instantiates a new LLMProviderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMProviderResponseWithDefaults() *LLMProviderResponse {
	this := LLMProviderResponse{}
	return &this
}

// GetId returns the Id field value
func (o *LLMProviderResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LLMProviderResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *LLMProviderResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LLMProviderResponse) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *LLMProviderResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *LLMProviderResponse) SetVersion(v string) {
	o.Version = v
}

// GetTemplate returns the Template field value
func (o *LLMProviderResponse) GetTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *LLMProviderResponse) SetTemplate(v string) {
	o.Template = v
}

// GetUpstream returns the Upstream field value if set, zero value otherwise.
func (o *LLMProviderResponse) GetUpstream() map[string]interface{} {
	if o == nil || IsNil(o.Upstream) {
		var ret map[string]interface{}
		return ret
	}
	return o.Upstream
}

// GetUpstreamOk returns a tuple with the Upstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetUpstreamOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Upstream) {
		return map[string]interface{}{}, false
	}
	return o.Upstream, true
}

// HasUpstream returns a boolean if a field has been set.
func (o *LLMProviderResponse) HasUpstream() bool {
	if o != nil && !IsNil(o.Upstream) {
		return true
	}

	return false
}

// SetUpstream gets a reference to the given map[string]interface{} and assigns it to the Upstream field.
func (o *LLMProviderResponse) SetUpstream(v map[string]interface{}) {
	o.Upstream = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LLMProviderResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LLMProviderResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LLMProviderResponse) SetDescription(v string) {
	o.Description = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *LLMProviderResponse) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *LLMProviderResponse) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *LLMProviderResponse) SetContext(v string) {
	o.Context = &v
}

// GetVhost returns the Vhost field value
func (o *LLMProviderResponse) GetVhost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vhost
}

// GetVhostOk returns a tuple with the Vhost field value
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetVhostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vhost, true
}

// SetVhost sets field value
func (o *LLMProviderResponse) SetVhost(v string) {
	o.Vhost = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *LLMProviderResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *LLMProviderResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *LLMProviderResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *LLMProviderResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetGateways returns the Gateways field value if set, zero value otherwise.
func (o *LLMProviderResponse) GetGateways() []GatewaySummary {
	if o == nil || IsNil(o.Gateways) {
		var ret []GatewaySummary
		return ret
	}
	return o.Gateways
}

// GetGatewaysOk returns a tuple with the Gateways field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMProviderResponse) GetGatewaysOk() ([]GatewaySummary, bool) {
	if o == nil || IsNil(o.Gateways) {
		return nil, false
	}
	return o.Gateways, true
}

// HasGateways returns a boolean if a field has been set.
func (o *LLMProviderResponse) HasGateways() bool {
	if o != nil && !IsNil(o.Gateways) {
		return true
	}

	return false
}

// SetGateways gets a reference to the given []GatewaySummary and assigns it to the Gateways field.
func (o *LLMProviderResponse) SetGateways(v []GatewaySummary) {
	o.Gateways = v
}

func (o LLMProviderResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMProviderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["template"] = o.Template
	if !IsNil(o.Upstream) {
		toSerialize["upstream"] = o.Upstream
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	toSerialize["vhost"] = o.Vhost
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	if !IsNil(o.Gateways) {
		toSerialize["gateways"] = o.Gateways
	}
	return toSerialize, nil
}

type NullableLLMProviderResponse struct {
	value *LLMProviderResponse
	isSet bool
}

func (v NullableLLMProviderResponse) Get() *LLMProviderResponse {
	return v.value
}

func (v *NullableLLMProviderResponse) Set(val *LLMProviderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMProviderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMProviderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMProviderResponse(val *LLMProviderResponse) *NullableLLMProviderResponse {
	return &NullableLLMProviderResponse{value: val, isSet: true}
}

func (v NullableLLMProviderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMProviderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
