{{- if and .Values.jwtKeysGeneration.enabled (not .Values.jwtSigning.existingSecret) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: amp-jwt-keys-generation
  labels:
    {{- include "agent-management-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: jwt-keys-generation
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.jwtKeysGeneration.backoffLimit }}
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: amp-jwt-keys-generation
      labels:
        {{- include "agent-management-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: jwt-keys-generation
    spec:
      {{- include "agent-management-platform.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "agent-management-platform.serviceAccountName" . }}
      restartPolicy: Never
      {{- with .Values.jwtKeysGeneration.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: jwt-keys-generation
          {{- with .Values.jwtKeysGeneration.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "alpine:3.21"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -euo pipefail
              
              # Install required tools
              apk add --no-cache openssl kubectl curl
              
              # Check if secret already exists
              if kubectl get secret {{ include "agent-management-platform.jwtKeysSecretName" . }} -n {{ .Release.Namespace }} &>/dev/null; then
                echo "JWT keys Secret already exists, skipping generation"
                exit 0
              fi
              
              echo "Generating JWT signing keys..."
              mkdir -p /tmp/keys
              cd /tmp/keys
              
              # Generate RSA private key (4096 bits for security)
              openssl genrsa -out private.pem 4096
              
              # Extract public key
              openssl rsa -in private.pem -pubout -out public.pem
              
              # Use configured key ID from agentManagerService config
              KEY_ID="{{ .Values.agentManagerService.config.jwtSigning.activeKeyId }}"
              ISSUER="{{ .Values.agentManagerService.config.jwtSigning.issuer }}"
              TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
              
              # Create public-keys-config.json
              cat > public-keys-config.json <<EOF
              {
                "keys": [
                  {
                    "keyId": "${KEY_ID}",
                    "publicKey": "$(awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' public.pem)",
                    "algorithm": "RS256",
                    "issuer": "${ISSUER}",
                    "createdAt": "${TIMESTAMP}",
                    "expiresAt": null,
                    "isActive": true
                  }
                ]
              }
              EOF
              
              # Verify keys were generated
              if [[ ! -f private.pem ]] || [[ ! -f public.pem ]] || [[ ! -f public-keys-config.json ]]; then
                echo "ERROR: Key generation failed - missing key files"
                exit 1
              fi
              
              echo "Creating Kubernetes Secret with JWT keys..."
              kubectl create secret generic {{ include "agent-management-platform.jwtKeysSecretName" . }} \
                -n {{ .Release.Namespace }} \
                --from-file=private.pem=private.pem \
                --from-file=public.pem=public.pem \
                --from-file=public-keys-config.json=public-keys-config.json \
                --dry-run=client -o yaml | \
              kubectl apply -f -
              
              # Add annotations for tracking
              kubectl annotate secret {{ include "agent-management-platform.jwtKeysSecretName" . }} \
                -n {{ .Release.Namespace }} \
                amp.wso2.com/keys-version="1" \
                amp.wso2.com/key-id="${KEY_ID}" \
                amp.wso2.com/generated-at="${TIMESTAMP}" \
                --overwrite
              
              echo "JWT keys Secret created successfully with key ID: ${KEY_ID}"
          {{- with .Values.jwtKeysGeneration.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
